"""[watermark] v137 콘텐츠 신뢰 — MAIDOL 워터마크 공용 헬퍼 (BE-2).

가시: ffmpeg drawtext "MAIDOL · AI 생성" 필터 문자열 조립
      (share_video 3포맷 + mv_generator 최종 concat pass 공용).
비가시:
  - 이미지: embed_image_metadata(bytes) — PNG tEXt / JPEG EXIF 에
    "AI-Generated|MAIDOL|{ISO날짜}" 삽입. 픽셀 데이터 재인코딩 없음
    (PNG 는 tEXt 청크 스플라이스, JPEG 는 APP1 EXIF 세그먼트만 조작) —
    품질 저하 0. 실패 시 원본 그대로 반환 (생성 흐름 무중단).
  - 영상: video_metadata_args() — ffmpeg -metadata comment="AI-Generated by MAIDOL".
"""

import logging
import os
import struct
import zlib
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

# 브랜드 표기 — 정확히 "MAIDOL · AI 생성" (AIDOL 아님 — MAIDOL 상표 선점, v137).
BRAND_TEXT = "MAIDOL · AI 생성"

# 영상 컨테이너 메타데이터 comment 값.
VIDEO_COMMENT = "AI-Generated by MAIDOL"

# 이미지 메타데이터 마커 prefix — 뒤에 ISO 날짜(UTC)가 붙는다.
IMAGE_MARKER_PREFIX = "AI-Generated|MAIDOL|"

# 번들 폰트 (share_video 자막과 동일 NanumGothic — OFL 라이선스).
FONTS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "fonts"
)
FONT_FILE = os.path.join(FONTS_DIR, "NanumGothic-Regular.ttf")

_PNG_SIG = b"\x89PNG\r\n\x1a\n"


def image_marker_text() -> str:
    """비가시 이미지 마커 문자열 — "AI-Generated|MAIDOL|YYYY-MM-DD" (UTC)."""
    return IMAGE_MARKER_PREFIX + datetime.now(timezone.utc).date().isoformat()


def video_metadata_args() -> list:
    """ffmpeg 출력 옵션에 끼워 넣는 컨테이너 메타데이터 인자."""
    return ["-metadata", "comment={}".format(VIDEO_COMMENT)]


def _escape_filter_path(path: str) -> str:
    """ffmpeg 필터 인자용 경로 이스케이프 — `'`/`:`/`\\` (share_video 와 동일 규칙)."""
    return path.replace("\\", "\\\\").replace("'", "\\'").replace(":", "\\:")


def build_drawtext(
    fontsize: int, x: str = "w-tw-40", y: str = "h-th-40"
) -> str:
    """가시 워터마크 drawtext 필터 문자열.

    흰색 alpha 0.6 + 얇은 검정 보더/그림자 (밝은·어두운 배경 모두 가독).
    기본 위치 우하단 (x/y 는 포맷별 오버라이드 — kakao 는 y=h*0.55 등).
    """
    return (
        "drawtext=fontfile='{font}':text='{text}':fontcolor=white@0.6:"
        "fontsize={fs}:borderw=1:bordercolor=black@0.45:"
        "shadowx=1:shadowy=1:shadowcolor=black@0.4:x={x}:y={y}"
    ).format(
        font=_escape_filter_path(FONT_FILE),
        text=BRAND_TEXT,
        fs=fontsize,
        x=x,
        y=y,
    )


# ── 비가시 이미지 메타데이터 ────────────────────────────────────────────────


def _png_insert_text(data: bytes, text: str) -> bytes:
    """PNG 에 tEXt 청크(Comment=text) 삽입 — IHDR 직후, 픽셀 데이터 무변경."""
    if not data.startswith(_PNG_SIG):
        raise ValueError("not a PNG")
    ihdr_len = struct.unpack(">I", data[8:12])[0]
    if data[12:16] != b"IHDR":
        raise ValueError("PNG missing IHDR")
    insert_at = 8 + 8 + ihdr_len + 4  # sig + (len+type) + data + crc
    payload = b"Comment\x00" + text.encode("ascii")
    chunk = (
        struct.pack(">I", len(payload))
        + b"tEXt"
        + payload
        + struct.pack(">I", zlib.crc32(b"tEXt" + payload) & 0xFFFFFFFF)
    )
    return data[:insert_at] + chunk + data[insert_at:]


def _build_exif_app1(text: str) -> bytes:
    """EXIF APP1 세그먼트 조립 — ImageDescription(0x010E) + UserComment(0x9286)."""
    from PIL import Image

    exif = Image.Exif()
    exif[0x010E] = text  # ImageDescription (IFD0)
    try:
        # UserComment (Exif sub-IFD) — ASCII charset 헤더 8바이트 + 본문.
        exif.get_ifd(0x8769)[0x9286] = b"ASCII\x00\x00\x00" + text.encode("ascii")
    except Exception:
        pass  # sub-IFD 미지원 Pillow 이면 ImageDescription 만으로 충분
    payload = exif.tobytes()  # b"Exif\x00\x00" + TIFF
    if len(payload) + 2 > 0xFFFF:
        raise ValueError("EXIF payload too large")
    return b"\xff\xe1" + struct.pack(">H", len(payload) + 2) + payload


def _jpeg_insert_exif(data: bytes, text: str) -> bytes:
    """JPEG 에 EXIF APP1 삽입 (기존 Exif APP1 은 교체) — 압축 데이터 무변경."""
    if data[:2] != b"\xff\xd8":
        raise ValueError("not a JPEG")
    app1 = _build_exif_app1(text)
    out = bytearray(b"\xff\xd8")
    out += app1
    i = 2
    n = len(data)
    while i + 4 <= n and data[i] == 0xFF:
        marker = data[i + 1]
        if marker == 0xDA:  # SOS — 이후는 압축 스트림, 그대로 복사
            break
        if marker in (0x01, 0xD8) or 0xD0 <= marker <= 0xD7:  # standalone
            out += data[i:i + 2]
            i += 2
            continue
        seg_len = struct.unpack(">H", data[i + 2:i + 4])[0]
        seg = data[i:i + 2 + seg_len]
        # 기존 Exif APP1 은 스킵(우리 것으로 교체), 나머지 세그먼트 유지.
        if not (marker == 0xE1 and seg[4:10] == b"Exif\x00\x00"):
            out += seg
        i += 2 + seg_len
    out += data[i:]
    return bytes(out)


def embed_image_metadata(data: bytes, fmt: str | None = None) -> bytes:
    """생성 이미지 바이트에 비가시 AI 마커 삽입 후 반환.

    포맷은 매직 바이트로 판별 (fmt 힌트는 로그용). PNG → tEXt, JPEG → EXIF.
    그 외 포맷·실패 시 원본 바이트 그대로 반환 — 생성/저장 흐름을 절대 깨지 않음.
    """
    if not data or len(data) < 16:
        return data
    text = image_marker_text()
    # 중복 삽입 가드 (마커는 항상 파일 선두부 메타데이터 영역에 위치).
    if IMAGE_MARKER_PREFIX.encode("ascii") in data[:4096]:
        return data
    try:
        if data.startswith(_PNG_SIG):
            out = _png_insert_text(data, text)
            kind = "png"
        elif data[:2] == b"\xff\xd8":
            out = _jpeg_insert_exif(data, text)
            kind = "jpeg"
        else:
            logger.info("[watermark] embed skip — unknown image format (fmt=%s)", fmt)
            return data
        logger.info(
            "[watermark] image metadata embedded kind=%s bytes=%d->%d",
            kind, len(data), len(out),
        )
        return out
    except Exception as e:  # noqa: BLE001
        logger.warning(
            "[watermark] embed failed (%s: %s) — 원본 유지",
            type(e).__name__, str(e)[:120],
        )
        return data
