"""
[share-video] SNS 공유영상 생성 서비스 (v126, v128 자막 burn-in, v129 3포맷, v137 워터마크).

커버 이미지(스틸) + 음원 → mp4 생성 후 MinIO(minio_bucket_music) 캐시.
타임스탬프(generations.variants[].timestamps) 보유 트랙은 가사 자막 burn-in (v128).

v129 포맷 (v137 캐시 v2→v3 승격 — 가시 워터마크 "MAIDOL · AI 생성" 전 포맷 burn-in):
- sns: 9:16 1080x1920 crop-fill, 곡 전체, 자막 하단 — share/v3/{id}.mp4
- wide: 16:9 1920x1080, 블러 배경+중앙 커버, 곡 전체, 자막 하단 — share/v3/{id}_wide.mp4
- kakao: 1080x2340 crop-fill, 첫 가사−0.5s 부터 15초 클립, 자막 상단 — share/v3/{id}_kakao.mp4

v137 [watermark]: drawtext 우하단 + 컨테이너 메타데이터 comment="AI-Generated by MAIDOL".
무자막 영상에도 워터마크는 항상 적용.

v152 [scroll]: burn-in 가사를 브라우저 가사 뷰(v150) 처럼 스크롤 렌더 — 현재 줄이
중앙에 확대·강조되고 이웃 줄은 흐리게, 전체 스택이 위로 glide (ASS \\an5 + \\move,
ffmpeg/libass 전용, 신규 의존성 없음). 시각 출력 변경 → 캐시 v3→v4 승격.
스크롤 빌더 실패 시 기존 단일 줄(_build_ass) 로 폴백. 자막 프레임레이트 10→20fps.
"""

import logging
import os
import re
import subprocess
import tempfile
import time

import httpx

from ..config import settings
from ..database.minio import get_minio
from .mv_generator import _get_ffmpeg_path
from .watermark import build_drawtext, video_metadata_args

logger = logging.getLogger(__name__)

SHARE_VIDEO_TIMEOUT = 300  # seconds

# 번들 폰트 디렉토리 (app/assets/fonts — NanumGothic-Regular.ttf, OFL 라이선스)
FONTS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "fonts"
)

# `[Verse]`, `[Chorus]` 등 전체가 대괄호인 섹션 태그 줄 — 가사 아님, 자막 스킵
_SECTION_TAG_RE = re.compile(r"^\[.*\]$")


class ShareVideoError(Exception):
    """공유영상 생성 실패 (라우터에서 502 로 매핑)."""


# 자막 선행 초 — 보컬보다 살짝 먼저 띄움 (체감상 "늦다" 방지, 조정 가능)
SUBTITLE_LEAD = 0.3

# v129 포맷 정의 — sns 는 기존(v128) 값 불변 (캐시 재사용 필수)
KAKAO_CLIP_SECONDS = 15.0
FORMATS = {
    "sns": {
        "width": 1080, "height": 1920, "suffix": "",
        "ass": {"fontsize": 64, "alignment": 2, "margin_v": 380},
        "clip": None,
    },
    "wide": {
        "width": 1920, "height": 1080, "suffix": "_wide",
        "ass": {"fontsize": 56, "alignment": 2, "margin_v": 80},
        "clip": None,
    },
    "kakao": {
        "width": 1080, "height": 2340, "suffix": "_kakao",
        "ass": {"fontsize": 60, "alignment": 8, "margin_v": 600},
        "clip": KAKAO_CLIP_SECONDS,
    },
}


# v137 가시 워터마크 배치 (FORMATS 값 불변 — 워터마크 스펙은 별도 유지):
# - sns: 우하단(자막 MarginV 380 권역 밖 — 하단 40px)
# - wide: 우하단(자막 MarginV 80 → 워터마크 상단이 자막 하한(1000px)보다 아래인 y=h-th-20)
# - kakao: 우측이되 y=h*0.55 — 상단 자막권(MarginV 600) 밖 + 카톡 프로필 하단 40% UI
#   가림 영역(y>1404) 위
_WATERMARK = {
    "sns": {"fontsize": 36, "x": "w-tw-40", "y": "h-th-40"},
    "wide": {"fontsize": 40, "x": "w-tw-40", "y": "h-th-20"},
    "kakao": {"fontsize": 36, "x": "w-tw-40", "y": "h*0.55"},
}


def share_object_name(track_id: str, fmt: str = "sns") -> str:
    # v137: 워터마크 도입으로 캐시 버전 v2 → v3 승격 (기존 v2 객체는 일괄 삭제됨).
    # v152: 스크롤 자막 도입으로 시각 출력 변경 → v3 → v4 승격 (기존 v3 캐시는
    #       구버전 단일 줄 자막이므로 서빙 금지, 자동으로 v4 신규 생성됨).
    suffix = FORMATS.get(fmt, FORMATS["sns"])["suffix"]
    return f"share/v4/{track_id}{suffix}.mp4"


def _filter_segments(raw: list) -> list:
    """타임스탬프 원본 목록 → 자막용 세그먼트 필터·보정 (공용, v130 추출).

    섹션 태그 줄(`[Verse]` 등)·빈 text·start<0·비수치 스킵, end<=start → +0.5,
    SUBTITLE_LEAD 선행 적용. generation·recognized 양쪽 경로에서 사용.
    """
    if not isinstance(raw, list):
        return []
    segments = []
    for seg in raw:
        if not isinstance(seg, dict):
            continue
        text = str(seg.get("text") or "").strip()
        if not text or _SECTION_TAG_RE.match(text):
            continue
        try:
            start = float(seg.get("start"))
            end = float(seg.get("end"))
        except (TypeError, ValueError):
            continue
        if start < 0:
            continue
        if end <= start:
            end = start + 0.5
        # 자막 리드(선행): Suno 타임스탬프가 체감 보컬 시작보다 늦게 잡히는 경향이
        # 있어 노래방 방식으로 전체를 SUBTITLE_LEAD 만큼 앞당긴다 (시작·끝 동시
        # 이동 — 줄 간 겹침 없음). 사용자 체감 피드백 기반 (2026-07-23).
        start = max(0.0, start - SUBTITLE_LEAD)
        end = max(start + 0.3, end - SUBTITLE_LEAD)
        segments.append({"text": text, "start": start, "end": end})
    return segments


async def _fetch_lyric_segments(mongo, track: dict) -> list:
    """트랙 → 가사 타임스탬프 세그먼트 조회 (async/motor).

    1순위: generations.variants[variant_index or 0].timestamps (기존 경로 불변).
    2순위(v130 폴백): 결과가 [] 이면 track.recognized_timestamps (Wondera recognize
    파이프라인 저장분)를 동일 필터로 처리. 둘 다 없으면 [].
    """
    segments = _filter_segments(await _generation_timestamps(mongo, track))
    source = "generation" if segments else "none"
    if not segments:
        recognized = _filter_segments(track.get("recognized_timestamps") or [])
        if recognized:
            segments = recognized
            source = "recognized"
    logger.info(
        "[share-video] lyric segments source=%s count=%d track=%s",
        source, len(segments), str(track.get("_id", ""))[:8],
    )
    return segments


async def _generation_timestamps(mongo, track: dict) -> list:
    """generation 경로 원본 타임스탬프 조회 — 필터 전 raw 목록 (없으면 [])."""
    generation_id = track.get("generation_id")
    if not generation_id:
        return []
    try:
        from bson import ObjectId

        query_id = (
            ObjectId(generation_id)
            if isinstance(generation_id, str) and ObjectId.is_valid(generation_id)
            else generation_id
        )
        gen = await mongo.generations.find_one({"_id": query_id}, {"variants": 1})
    except Exception:
        logger.warning("[share-video] generations lookup failed gen=%s", generation_id)
        return []
    if not gen:
        return []
    variants = gen.get("variants")
    if not isinstance(variants, list) or not variants:
        return []
    idx = track.get("variant_index") or 0
    if not isinstance(idx, int) or idx < 0 or idx >= len(variants):
        idx = 0
    variant = variants[idx]
    timestamps = variant.get("timestamps") if isinstance(variant, dict) else None
    return timestamps if isinstance(timestamps, list) else []


def _ass_time(seconds: float) -> str:
    """초(float) → ASS 타임스탬프 h:mm:ss.cs"""
    cs = int(round(seconds * 100))
    h, rem = divmod(cs, 360000)
    m, rem = divmod(rem, 6000)
    s, c = divmod(rem, 100)
    return f"{h}:{m:02d}:{s:02d}.{c:02d}"


def _build_ass(segments: list, fmt: str = "sns") -> str:
    """세그먼트 → ASS 자막 문자열 (포맷별 PlayRes/Alignment/MarginV, NanumGothic)."""
    spec = FORMATS.get(fmt, FORMATS["sns"])
    ass = spec["ass"]
    header = (
        "[Script Info]\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {spec['width']}\n"
        f"PlayResY: {spec['height']}\n"
        "WrapStyle: 0\n"
        "ScaledBorderAndShadow: yes\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        f"Style: Default,NanumGothic,{ass['fontsize']},&H00FFFFFF,&H00FFFFFF,&H00000000,"
        f"&H00000000,0,0,0,0,100,100,0,0,1,3,0,{ass['alignment']},40,40,{ass['margin_v']},1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
    )
    lines = []
    for seg in segments:
        text = seg["text"].replace("{", "(").replace("}", ")")
        text = text.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\\N")
        lines.append(
            f"Dialogue: 0,{_ass_time(seg['start'])},{_ass_time(seg['end'])},"
            f"Default,,0,0,0,,{text}\n"
        )
    return header + "".join(lines)


# v152 [scroll] 스크롤 자막 레이아웃 — 현재 줄 중앙(\an5) Y=cy, 줄 높이 rh, 표시창 ±window.
# cy/rh 는 워터마크(_WATERMARK) 권역과 화면 경계를 침범하지 않도록 포맷별 튜닝:
#   최하단 줄 중앙 = cy + window*rh, 최상단 줄 중앙 = cy - window*rh.
# - sns  h1920 워터마크 y≈1844: 최하단 1380+2*110=1600 (< 1844) ✓ / 최상단 1160 ✓
# - wide h1080 워터마크 y≈1020: 최하단 720+2*90=900  (< 1020) ✓ / 최상단 540 ✓
# - kakao h2340 워터마크 y≈1287: 최하단 820+2*105=1030 (< 1287) ✓ / 최상단 610 ✓
SCROLL_LAYOUT = {
    "sns": {"cy": 1380, "rh": 110, "window": 2},
    "wide": {"cy": 720, "rh": 90, "window": 2},
    "kakao": {"cy": 820, "rh": 105, "window": 2},
}


def _emph_state(mag: int) -> tuple:
    """스크롤 자막 강조 상태 (거리 |offset| → (alpha, scale%)).

    현재 줄(0)은 불투명·확대, 멀어질수록 흐려지고 축소, 창 밖(>=3)은 완전 투명
    (아래에서 fade-in 하는 진입 줄의 시작 상태로 사용)."""
    if mag <= 0:
        return ("&H00&", 110)
    if mag == 1:
        return ("&H55&", 100)
    if mag == 2:
        return ("&H90&", 92)
    return ("&HFF&", 88)


def _build_ass_scroll(segments: list, fmt: str = "sns") -> str:
    """세그먼트 → 스크롤 ASS 자막 문자열 (v152, 브라우저 가사 뷰 v150 미러).

    각 활성 구간 [T_a, T_{a+1}) 마다 현재 줄 a 를 중앙(cy)에 두고 ±window 이웃 줄을
    위/아래 슬롯에 배치. 구간 전환 시 모든 줄이 \\move 로 한 슬롯(rh) 위로 glide 하고
    \\t 로 강조(alpha/scale)를 동시에 보간 → 스택이 매끄럽게 위로 스크롤.
    T_a = segments[a].start, 마지막 경계 T_N = segments[N-1].end.
    실패 없이 항상 문자열 반환 (예외는 호출부에서 잡아 _build_ass 로 폴백)."""
    spec = FORMATS.get(fmt, FORMATS["sns"])
    ass = spec["ass"]
    layout = SCROLL_LAYOUT.get(fmt, SCROLL_LAYOUT["sns"])
    cy, rh, window = layout["cy"], layout["rh"], layout["window"]
    x = spec["width"] // 2

    header = (
        "[Script Info]\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {spec['width']}\n"
        f"PlayResY: {spec['height']}\n"
        "WrapStyle: 0\n"
        "ScaledBorderAndShadow: yes\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        # Alignment=5 (\an5, 중앙 앵커) — 줄별로 \pos/\move 의 Y 가 세로 중앙점.
        f"Style: Default,NanumGothic,{ass['fontsize']},&H00FFFFFF,&H00FFFFFF,&H00000000,"
        f"&H00000000,0,0,0,0,100,100,0,0,1,3,0,5,40,40,0,1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
    )

    n = len(segments)
    if n == 0:
        return header

    # 활성 경계: T[a] = segments[a].start (a<n), 마지막 T[n] = segments[n-1].end.
    bounds = [float(seg["start"]) for seg in segments]
    bounds.append(float(segments[n - 1]["end"]))

    def esc(raw: str) -> str:
        t = str(raw).replace("{", "(").replace("}", ")")
        return t.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\\N")

    events = []
    for a in range(n):
        t_start = bounds[a]
        t_end = bounds[a + 1]
        period = t_end - t_start
        if period <= 0:
            continue
        d = min(0.45, period / 2.0)
        d_ms = max(1, int(round(d * 1000)))
        start_ts = _ass_time(t_start)
        end_ts = _ass_time(t_end)
        for k in range(-window, window + 1):
            j = a + k
            if j < 0 or j >= n:
                continue
            y_cur = cy + k * rh
            y_prev = cy + (k + 1) * rh  # 이전 구간에서 이 줄이 있던 한 슬롯 아래 위치
            target_alpha, target_scale = _emph_state(abs(k))
            if a == 0:
                # 첫 구간: 이전 상태 없음 → 이동/보간 없이 목표 위치·강조로 즉시 배치.
                override = (
                    f"\\an5\\pos({x},{y_cur})\\1c&HFFFFFF&"
                    f"\\alpha{target_alpha}\\fscx{target_scale}\\fscy{target_scale}"
                )
            else:
                origin_alpha, origin_scale = _emph_state(abs(k + 1))
                override = (
                    f"\\an5\\move({x},{y_prev},{x},{y_cur},0,{d_ms})\\1c&HFFFFFF&"
                    f"\\alpha{origin_alpha}\\fscx{origin_scale}\\fscy{origin_scale}"
                    f"\\t(0,{d_ms},\\alpha{target_alpha}"
                    f"\\fscx{target_scale}\\fscy{target_scale})"
                )
            text = esc(segments[j]["text"])
            events.append(
                f"Dialogue: 0,{start_ts},{end_ts},Default,,0,0,0,,"
                f"{{{override}}}{text}\n"
            )
    return header + "".join(events)


def share_video_exists(track_id: str, fmt: str = "sns") -> bool:
    """MinIO 에 캐시된 공유영상이 있는지 확인 (blocking)."""
    minio_client = get_minio()
    try:
        minio_client.stat_object(
            bucket_name=settings.minio_bucket_music,
            object_name=share_object_name(track_id, fmt),
        )
        return True
    except Exception:
        return False


def _download_cover(minio_client, cover_image_url: str, dest_path: str) -> None:
    """커버 다운로드 — 외부 URL(http/https)이면 httpx, 아니면 이미지 버킷 object."""
    if cover_image_url.startswith(("http://", "https://")):
        resp = httpx.get(cover_image_url, timeout=30.0, follow_redirects=True)
        resp.raise_for_status()
        with open(dest_path, "wb") as f:
            f.write(resp.content)
        return
    response = minio_client.get_object(
        bucket_name=settings.minio_bucket_images,
        object_name=cover_image_url,
    )
    try:
        with open(dest_path, "wb") as f:
            for chunk in response.stream(64 * 1024):
                f.write(chunk)
    finally:
        response.close()
        response.release_conn()


def _download_audio(minio_client, audio_url: str, dest_path: str) -> None:
    response = minio_client.get_object(
        bucket_name=settings.minio_bucket_music,
        object_name=audio_url,
    )
    try:
        with open(dest_path, "wb") as f:
            for chunk in response.stream(64 * 1024):
                f.write(chunk)
    finally:
        response.close()
        response.release_conn()


def _probe_audio_duration(ffmpeg_path: str, audio_path: str) -> float:
    """음원 길이(초) 추출 — 실패 시 0.0 (그 경우 -shortest 만으로 동작)."""
    ffprobe = os.path.join(os.path.dirname(ffmpeg_path), "ffprobe")
    if not os.path.exists(ffprobe):
        ffprobe = "ffprobe"
    try:
        proc = subprocess.run(
            [ffprobe, "-v", "error", "-show_entries", "format=duration",
             "-of", "csv=p=0", audio_path],
            capture_output=True, timeout=30,
        )
        return float(proc.stdout.decode().strip()) if proc.returncode == 0 else 0.0
    except Exception:
        return 0.0


def _filter_path(path: str) -> str:
    """ffmpeg 필터 인자용 경로 안전 조립 — `'`/`:`/`\\` 이스케이프."""
    return path.replace("\\", "\\\\").replace("'", "\\'").replace(":", "\\:")


def generate_share_video(
    track_id: str,
    cover_image_url: str,
    audio_url: str,
    segments: list | None = None,
    fmt: str = "sns",
) -> int:
    """커버+음원 다운로드 → ffmpeg 스틸영상 생성 → MinIO 업로드 (blocking).

    segments(v128): 가사 타임스탬프 목록 — 있으면 ASS 자막 burn-in(-r 10).
    fmt(v129): sns(9:16 전체) / wide(16:9 블러배경) / kakao(1080x2340 15s 클립).
    Returns: 생성된 mp4 크기(bytes). 실패 시 ShareVideoError.
    """
    ffmpeg = _get_ffmpeg_path()
    if not ffmpeg:
        raise ShareVideoError("ffmpeg not available")
    if fmt not in FORMATS:
        raise ShareVideoError(f"unknown format: {fmt}")
    spec = FORMATS[fmt]

    segments = segments or []
    # kakao(v129): 15초 클립 — t0 = 첫 가사 세그먼트 start−0.5s(음수면 0, 세그먼트 없으면 0).
    # ASS 시각은 t0 기준으로 offset 보정, 클립(0~15s) 범위 세그먼트만 포함.
    clip_t0 = 0.0
    clip_len = spec["clip"]
    if clip_len:
        if segments:
            clip_t0 = max(0.0, segments[0]["start"] - 0.5)
        clipped = []
        for seg in segments:
            start = seg["start"] - clip_t0
            end = min(seg["end"] - clip_t0, clip_len)
            if 0 <= start < clip_len and end > start:
                clipped.append({"text": seg["text"], "start": start, "end": end})
        logger.info(
            "[share-video] kakao clip track=%s t0=%.2f segments=%d→%d",
            track_id, clip_t0, len(segments), len(clipped),
        )
        segments = clipped
    subtitled = bool(segments)
    minio_client = get_minio()
    with tempfile.TemporaryDirectory(prefix="share_video_") as tmp_dir:
        cover_ext = os.path.splitext(cover_image_url.split("?")[0])[1] or ".png"
        audio_ext = os.path.splitext(audio_url)[1] or ".mp3"
        cover_path = os.path.join(tmp_dir, f"cover{cover_ext}")
        audio_path = os.path.join(tmp_dir, f"audio{audio_ext}")
        out_path = os.path.join(tmp_dir, "out.mp4")

        try:
            _download_cover(minio_client, cover_image_url, cover_path)
        except Exception as e:
            raise ShareVideoError(f"cover download failed: {e}") from e
        try:
            _download_audio(minio_client, audio_url, audio_path)
        except Exception as e:
            raise ShareVideoError(f"audio download failed: {e}") from e

        width, height = spec["width"], spec["height"]
        if fmt == "wide":
            # 커버 split → (배경) 확대 crop-fill + 블러, (전경) 세로 900 중앙 overlay
            vf = (
                "[0:v]split=2[bg][fg];"
                f"[bg]scale={width}:{height}:force_original_aspect_ratio=increase,"
                f"crop={width}:{height},boxblur=20:2[b];"
                "[fg]scale=-2:900[f];"
                "[b][f]overlay=(W-w)/2:(H-h)/2"
            )
        else:
            # 커버가 화면을 다 못 채우면 확대 후 중앙 크롭으로 꽉 채움 (sns/kakao)
            vf = (
                f"[0:v]scale={width}:{height}:force_original_aspect_ratio=increase,"
                f"crop={width}:{height}"
            )
        if subtitled:
            ass_path = os.path.join(tmp_dir, "subs.ass")
            # v152: 스크롤 자막 우선 — 실패 시 기존 단일 줄(_build_ass) 로 폴백.
            try:
                ass_body = _build_ass_scroll(segments, fmt)
                events_count = ass_body.count("Dialogue:")
                logger.info(
                    "[share-video] ass-scroll track=%s format=%s segments=%d "
                    "events=%d fps=20",
                    track_id, fmt, len(segments), events_count,
                )
            except Exception:
                logger.exception(
                    "[share-video] ass-scroll failed, fallback to single-line "
                    "track=%s format=%s",
                    track_id, fmt,
                )
                ass_body = _build_ass(segments, fmt)
            with open(ass_path, "w", encoding="utf-8") as f:
                f.write(ass_body)
            logger.info(
                "[share-video] ass build track=%s format=%s segments=%d fontsdir=%s",
                track_id, fmt, len(segments), FONTS_DIR,
            )
            vf += f",ass='{_filter_path(ass_path)}':fontsdir='{_filter_path(FONTS_DIR)}'"
        # v137 [watermark]: 가시 워터마크 — 자막 유무와 무관하게 항상 마지막에 적용.
        wm = _WATERMARK[fmt]
        vf += "," + build_drawtext(wm["fontsize"], x=wm["x"], y=wm["y"])
        logger.info(
            "[watermark] share drawtext track=%s format=%s fontsize=%d y=%s",
            track_id, fmt, wm["fontsize"], wm["y"],
        )
        vf += "[v]"
        # 자막 있으면 -r 20 (v152 스크롤 glide 부드럽게), 없으면 기존 -r 2 (스틸) — 3포맷 공통
        frame_rate = "20" if subtitled else "2"
        cmd = [ffmpeg, "-y", "-loop", "1", "-i", cover_path]
        if clip_len and clip_t0 > 0:
            cmd += ["-ss", f"{clip_t0:.3f}"]  # 음원 입력 seek (kakao 클립 시작점)
        cmd += [
            "-i", audio_path,
            "-filter_complex", vf,
            "-map", "[v]", "-map", "1:a",
            "-c:v", "libx264", "-tune", "stillimage", "-preset", "veryfast",
            "-r", frame_rate, "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "192k",
            "-shortest", "-movflags", "+faststart",
            # v137 [watermark]: 비가시 — 컨테이너 메타데이터 comment.
            *video_metadata_args(),
        ]
        # -loop 1 + -shortest 는 muxer interleave 로 영상이 음원보다 ~10s 길어질
        # 수 있어, 출력 길이를 -t 로 정확히 자름.
        # kakao: 고정 15s. 그 외: 음원 길이 probe (실패 시 -shortest 만).
        if clip_len:
            cmd += ["-t", f"{clip_len:.3f}"]
        else:
            audio_duration = _probe_audio_duration(ffmpeg, audio_path)
            if audio_duration > 0:
                cmd += ["-t", f"{audio_duration:.3f}"]
        cmd.append(out_path)
        started = time.monotonic()
        try:
            proc = subprocess.run(cmd, capture_output=True, timeout=SHARE_VIDEO_TIMEOUT)
        except subprocess.TimeoutExpired:
            logger.error(
                "[share-video] ffmpeg timeout track=%s format=%s (%ss)",
                track_id, fmt, SHARE_VIDEO_TIMEOUT,
            )
            raise ShareVideoError(f"ffmpeg timeout ({SHARE_VIDEO_TIMEOUT}s)")
        if proc.returncode != 0:
            stderr_tail = (proc.stderr or b"").decode("utf-8", errors="replace")[-500:]
            logger.error(
                "[share-video] ffmpeg failed track=%s format=%s rc=%s stderr_tail=%s",
                track_id, fmt, proc.returncode, stderr_tail,
            )
            raise ShareVideoError(f"ffmpeg rc={proc.returncode}")

        elapsed = time.monotonic() - started
        size = os.path.getsize(out_path)
        logger.info(
            "[share-video] ffmpeg done rc=0 track=%s format=%s elapsed=%.1fs size=%d bytes "
            "segments=%d subtitled=%s",
            track_id, fmt, elapsed, size, len(segments), subtitled,
        )

        # 동시 중복 생성 가드: 업로드 직전 재확인 — 이미 다른 요청이 올렸으면 스킵.
        if share_video_exists(track_id, fmt):
            logger.info(
                "[share-video] concurrent cache detected track=%s format=%s — skip upload",
                track_id, fmt,
            )
            return size

        with open(out_path, "rb") as f:
            minio_client.put_object(
                bucket_name=settings.minio_bucket_music,
                object_name=share_object_name(track_id, fmt),
                data=f,
                length=size,
                content_type="video/mp4",
            )
        return size
