"""
[share-video] SNS 공유영상 생성 서비스 (v126, v128 자막 burn-in, v129 3포맷, v137 워터마크).

커버 이미지(스틸) + 음원 → mp4 생성 후 MinIO(minio_bucket_music) 캐시.
타임스탬프(generations.variants[].timestamps) 보유 트랙은 가사 자막 burn-in (v128).

v129 포맷 (v137 캐시 v2→v3 승격 — 가시 워터마크 "MAIDOL · AI 생성" 전 포맷 burn-in):
- sns: 9:16 1080x1920 crop-fill, 곡 전체, 자막 하단 — share/v3/{id}.mp4
- wide: 16:9 1920x1080, 블러 배경+중앙 커버, 곡 전체, 자막 하단 — share/v3/{id}_wide.mp4
- kakao: 1080x2340 crop-fill, 첫 가사−0.5s 부터 15초 클립, 자막 상단 — share/v3/{id}_kakao.mp4

v137 [watermark]: drawtext 우하단 + 컨테이너 메타데이터 comment="AI-Generated by MAIDOL".
무자막 영상에도 워터마크는 항상 적용.

v152 [scroll]: burn-in 가사를 브라우저 가사 뷰(v150) 처럼 스크롤 렌더 — 현재 줄이
중앙에 확대·강조되고 이웃 줄은 흐리게, 전체 스택이 위로 glide (ASS \\an5 + \\move,
ffmpeg/libass 전용, 신규 의존성 없음). 시각 출력 변경 → 캐시 v3→v4 승격.
스크롤 빌더 실패 시 기존 단일 줄(_build_ass) 로 폴백. 자막 프레임레이트 10→20fps.

v3.214 (캐시 v6→v7 승격 — ④⑦⑧ 가시 출력 일괄 변경):
- ⑦ 자막 위치: _SUBPOS_MARGIN_V/_SUBPOS_SCROLL_CY 하드코딩 표 → _subpos_positions(fmt,
  layout) 기하 유도 함수. full 레이아웃은 기존 수치 그대로(회귀 0), center 는 "커버
  하단 ~ 워터마크 상단" 밴드 안 3단(wide 커버 0.5H→0.42H 상향, kakao 단일 클램프).
- ④ 가사 없는 곡(연주곡, Inst 파생 제외 — 라우트 판별)은 자막 대신 제목 drawtext —
  폭 초과 시에만 140px/s 우→좌 마퀴, 아니면 중앙 정적 (frame_rate 20).
- ⑧ 워터마크: 록업 PNG 1장 → PIL 런타임 스트립(좌 'AI 생성' 라운드 칩 + 우 MAIDOL
  록업(AI=#A855F7), 동일 fontsize·수직 중앙 정렬) overlay 합성.

v3.215 (인코딩 성능 — 캐시 v7→v8 승격):
- 정적 요소(커버 scale/crop, center 블러/어둠막/단색 배경+마스킹 커버 오버레이,
  wide 블러 배경+센터 커버, 워터마크 스트립)를 PIL 로 **배경 프레임 1장** 사전 합성
  (_compose_static_background). ffmpeg filter_complex 에는 동적 필터(ASS 자막,
  제목 마퀴 drawtext)만 남긴다 — -loop 입력 3개×overlay 2회가 매 프레임 재디코드
  되던 병목 제거 (EC2 실측: 순수 x264 60s=24.5s vs -loop+scale 47.5s).
- 유일한 -loop 1 이미지 입력에 -framerate 를 출력 -r 과 일치(자막/마퀴 20, 없으면 2)
  — 25fps 기본 디코드 낭비 제거.
- 기하 불변: 커버 위치·워터마크 y·밴드/subpos 좌표계는 기존 filter_complex 결과와
  동일(치환 대응표는 _compose_static_background docstring). 렌더 경로 변경이므로
  캐시 v8 승격 — 구 v7 은 자연 만료(삭제 금지), 보관함·프록시 하위호환.
"""

import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time

import httpx

from ..config import settings
from ..database.minio import get_minio
from .mv_generator import _get_ffmpeg_path
from .watermark import video_metadata_args

logger = logging.getLogger(__name__)

SHARE_VIDEO_TIMEOUT = 600  # seconds — v3.215: t3.large에서 fps20 장곡 인코딩이 동시 작업과 겹치면 300s를 넘김(실사고 2건). 여유 상향.


def _nice_cmd(cmd: list) -> list:
    """v3.258 [perf]: ffmpeg 인코딩 커맨드를 nice -n 10 으로 강등 (2026-09-28 성능 진단).

    t3.large 2vCPU 에서 share_video 의 ffmpeg 인코딩(실측 CPU 24~134s)이 단일
    uvicorn 워커와 코어를 경합해 API 지연을 만들던 것을, 스케줄러 우선순위만
    낮춰 완화한다. 리눅스(프로덕션 컨테이너)에서만 ["nice","-n","10"] 을
    prepend — nice 는 exec 로 ffmpeg 를 **대체**하므로 프로세스는 1개 그대로:
    subprocess.run 의 timeout(TimeoutExpired kill)·returncode·stderr 처리 경로가
    바이트 단위로 기존과 동일하다. nice 부재·비리눅스(맥 개발기)면 원본 그대로.
    ffprobe(_probe_audio_duration)는 경량 프로브라 대상에서 제외.
    madmom 박자분석 경로는 v3.244 로 OFF — 본 패치 무접촉.
    """
    if sys.platform.startswith("linux") and shutil.which("nice"):
        return ["nice", "-n", "10", *cmd]
    return list(cmd)

# 번들 폰트 디렉토리 (app/assets/fonts — NanumGothic-Regular.ttf, OFL 라이선스)
FONTS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "fonts"
)

# v3.182: 가시 워터마크 = 로고 록업 PNG — v3.214 부터 미사용 (PIL 런타임 스트립으로 대체,
# _make_watermark_strip 참조). 상수는 롤백 참조용으로만 유지.
WATERMARK_LOGO = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "watermark_logo.png"
)
# v3.214 ⑧: 워터마크 스트립(폭 W 전체, 투명 배경) overlay y 좌표 — x 는 항상 0.
#   kakao 만 카톡 프로필 UI 하단 가림 대비 y=H-h-56 (기존 록업 관행 유지).
_WATERMARK_STRIP_Y = {
    "sns": "H-h-20",
    "wide": "H-h-20",
    "kakao": "H-h-56",
}
# v3.215: 위 ffmpeg overlay y 식("H-h-<margin>")의 PIL 치환용 하단 마진 —
#   y = height - strip_h - margin (수치 동일: sns/wide 20, kakao 56).
#   _WATERMARK_STRIP_Y 는 치환 대응·롤백 참조용으로 유지.
_WATERMARK_STRIP_MARGIN = {"sns": 20, "wide": 20, "kakao": 56}
# v3.214 ⑧: 'AI 생성' 칩·MAIDOL 록업 텍스트 크기 — ≈ round(0.56 × 포맷 자막 fontsize)
# (sns 64→36 / wide 56→32 / kakao 60→34). "자막보다 작고, 구 록업(h40 내 ~20px)보다 큼".
_BADGE_FONTSIZE = {"sns": 36, "wide": 32, "kakao": 34}
# 앱 colors.accent.primary #A855F7 (상단바 로고 'AI' 색 — App.tsx LogoTitle 재현)
_BADGE_PURPLE = (168, 85, 247, 255)

# `[Verse]`, `[Chorus]` 등 전체가 대괄호인 섹션 태그 줄 — 가사 아님, 자막 스킵
_SECTION_TAG_RE = re.compile(r"^\[.*\]$")


class ShareVideoError(Exception):
    """공유영상 생성 실패 (라우터에서 502 로 매핑)."""


# 자막 선행 초 — 보컬보다 살짝 먼저 띄움 (체감상 "늦다" 방지, 조정 가능)
SUBTITLE_LEAD = 0.3

# v129 포맷 정의 — sns 는 기존(v128) 값 불변 (캐시 재사용 필수)
KAKAO_CLIP_SECONDS = 15.0
FORMATS = {
    "sns": {
        "width": 1080, "height": 1920, "suffix": "",
        "ass": {"fontsize": 64, "alignment": 2, "margin_v": 380},
        "clip": None,
    },
    "wide": {
        "width": 1920, "height": 1080, "suffix": "_wide",
        "ass": {"fontsize": 56, "alignment": 2, "margin_v": 80},
        "clip": None,
    },
    "kakao": {
        "width": 1080, "height": 2340, "suffix": "_kakao",
        "ass": {"fontsize": 60, "alignment": 8, "margin_v": 600},
        "clip": KAKAO_CLIP_SECONDS,
    },
}


# v137 가시 워터마크 배치 (FORMATS 값 불변 — 워터마크 스펙은 별도 유지):
# - sns: 우하단(자막 MarginV 380 권역 밖 — 하단 40px)
# - wide: 우하단(자막 MarginV 80 → 워터마크 상단이 자막 하한(1000px)보다 아래인 y=h-th-20)
# - kakao: 우측이되 y=h*0.55 — 상단 자막권(MarginV 600) 밖 + 카톡 프로필 하단 40% UI
#   가림 영역(y>1404) 위
_WATERMARK = {
    "sns": {"fontsize": 36, "x": "w-tw-40", "y": "h-th-40"},
    "wide": {"fontsize": 40, "x": "w-tw-40", "y": "h-th-20"},
    "kakao": {"fontsize": 36, "x": "w-tw-40", "y": "h*0.55"},
}


# v3.179(대표): 영상 스타일 축 — 영상 디렉터 대화에서 선택.
#   layout: full(현행 포맷별 기본 조성 — 캐시·과금 하위호환) | center(플레이어 느낌:
#           블러+어둠막 배경 위 정사각 커버를 중앙 상단에 오버레이)
#   shape:  square(둥근 모서리) | circle(원형) — center 레이아웃에서만 의미
#   lyrics: scroll(v152 스크롤 스택) | line(한 줄씩 — 기존 _build_ass 재사용)
STYLE_LAYOUTS = {"full", "center"}
STYLE_SHAPES = {"square", "circle"}
STYLE_LYRICS = {"scroll", "line"}
# v3.181(대표): 추가 스타일 축 — 폰트/글자색/배경 블러
STYLE_FONTS = {"basic", "round", "serif", "dohyeon", "jua"}
# v3.182: 글자색 = 키워드 4종 또는 hex6 (컬러 팔레트 — FE가 'FFD700' 형태로 전송)
STYLE_FONTCOLORS = {"white", "yellow", "pink", "sky"}
_HEX6_RE = re.compile(r"^[0-9a-fA-F]{6}$")
# v3.182: 배경 3모드 — clean(원본+어둠막) | blur(강도 light/mid/strong) | color(색+투명도)
STYLE_BGS = {"clean", "blur", "color"}
STYLE_BGBLURS = {"light", "mid", "strong"}
_BGBLUR_RADIUS = {"light": 10, "mid": 24, "strong": 44}
STYLE_BGALPHAS = {"25", "45", "70", "100"}  # v3.209: 100 = drawbox 완전 불투명(단색 배경 — 커버 완전 차폐)
# v3.209: 자막 테두리 on/off — "1"(기본, 테두리 두께 3)/"0"(테두리 없음)
STYLE_FONTOUTLINES = {"0", "1"}
# v3.183(대표): 자막 위치 — near(중앙 이미지 가까이)/mid/low(기존 하단). 라우트 'auto' 기본:
#   center 레이아웃이면 near(이미지 바로 아래 — 기존이 너무 아래라는 지적), full이면 low(현행 유지).
STYLE_SUBPOS = {"near", "mid", "low"}
# v3.214 ⑦: 자막 위치(subpos) 좌표 — 하드코딩 단일 표(_SUBPOS_MARGIN_V/_SUBPOS_SCROLL_CY)
# 를 레이아웃별 기하 유도 함수 _subpos_positions() 로 대체.
#
# full 레이아웃: 이미지가 전면 배경이라 겹침이 정상 — 기존 표 수치 그대로 (회귀 0).
# center 레이아웃: "커버 하단(ib)+pad20 ~ 워터마크 상단(wt)−pad20" 밴드 안 3단.
#   커버 기하(코드 동일 수식): size=min(W,H)×(0.68 | wide 0.60) 짝수보정,
#   수직 중심 = 0.32H (wide 는 v3.214 에서 0.5H→0.42H 상향 — 자막 밴드 확보).
#   ┌ fmt   ┬ 커버 점유   ┬ 밴드        ┬ scroll(window,rh) ┐
#   │ sns   │  247– 981   │ 1001–1840   │ ±2, 110           │
#   │ wide  │  130– 778   │  798–1000   │ ±1,  70           │
#   │ kakao │  382–1116   │ 1136–1384*  │ ±1,  90           │
#   └ *kakao 는 카톡 프로필 UI 가림(y>1404) 제약으로 밴드 248px — 3단 미분화,
#     near/mid/low 동일 클램프 (기존 kakao line 역전(low가 mid보다 위) 구조 소멸).
_SUBPOS_POSITIONS = {
    "full": {
        # 기존 _SUBPOS_MARGIN_V/_SUBPOS_SCROLL_CY 수치 그대로 (바이트 일치 — 회귀 0).
        "sns": {
            "margin_v": {"near": 760, "mid": 560, "low": 380},
            "scroll_cy": {"near": 1150, "mid": 1265, "low": 1380},
            "scroll_rh": 110, "scroll_window": 2,
        },
        "wide": {
            "margin_v": {"near": 150, "mid": 110, "low": 80},
            "scroll_cy": {"near": 650, "mid": 685, "low": 720},
            "scroll_rh": 90, "scroll_window": 2,
        },
        "kakao": {  # near=중앙 이미지(하단≈1116) 겹침 해소 (구 주석 유지)
            "margin_v": {"near": 1180, "mid": 900, "low": 600},
            "scroll_cy": {"near": 1180, "mid": 1000, "low": 820},
            "scroll_rh": 105, "scroll_window": 2,
        },
    },
    "center": {
        # scroll_cy: near=밴드 상단 진입, low=밴드 하단, mid=중간.
        # margin_v(line): sns/wide alignment=2(하단 기준), kakao alignment=8(상단 기준).
        "sns": {   # 1080×1920, 밴드 1001–1840
            "margin_v": {"near": 830, "mid": 470, "low": 110},
            "scroll_cy": {"near": 1221, "mid": 1421, "low": 1620},
            "scroll_rh": 110, "scroll_window": 2,
        },
        "wide": {  # 1920×1080, 커버 0.42H 상향 → 밴드 798–1000 (협소 — window ±1)
            "margin_v": {"near": 220, "mid": 150, "low": 80},  # near 230→220: 자막 상단이 밴드(798~) 안에 완전 안착(tester S-1④)
            "scroll_cy": {"near": 872, "mid": 906, "low": 940},
            "scroll_rh": 70, "scroll_window": 1,
        },
        "kakao": { # 1080×2340, 밴드 1136–1384 — 3단 단일 클램프 (미분화 문서화)
            "margin_v": {"near": 1136, "mid": 1136, "low": 1136},
            "scroll_cy": {"near": 1250, "mid": 1250, "low": 1250},
            "scroll_rh": 90, "scroll_window": 1,
        },
    },
}


def _subpos_positions(fmt: str, layout: str = "full") -> dict:
    """v3.214 ⑦: 포맷·레이아웃별 subpos 3단 좌표 (기하 유도 — 상단 표 참조).

    반환: {"margin_v": {near,mid,low}, "scroll_cy": {near,mid,low},
           "scroll_rh": int, "scroll_window": int}
    full 은 기존 하드코딩 표와 동일 수치 (캐시·회귀 무영향), center 는 커버·워터마크
    기하에서 유도한 밴드 좌표. 미지원 fmt/layout 은 full/sns 로 폴백.
    """
    by_fmt = _SUBPOS_POSITIONS.get(layout, _SUBPOS_POSITIONS["full"])
    return by_fmt.get(fmt, by_fmt["sns"])
# v3.209: 14원소 확장 — 말미 2축(fontoutline="1", outlinecolor="") 이 기본이면
# _style_suffix 에서 절단되어 기존 12원소 조합의 object name 이 비트 동일하게 보존됨.
_DEFAULT_STYLE_TUPLE = ("full", "square", "scroll", "basic", "white", "blur", "mid", "", "45", "0", "0", "low", "1", "")

# ASS Fontname 은 폰트 파일의 family 명과 일치해야 함 (assets/fonts 번들, OFL)
_FONT_NAME = {
    "basic": "NanumGothic", "round": "Gowun Dodum", "serif": "NanumMyeongjo",
    "dohyeon": "Do Hyeon", "jua": "Jua",
}
# v3.214 ④: drawtext(fontfile=)·PIL 용 실제 ttf 파일명 (assets/fonts 번들 실측)
_FONT_FILE = {
    "basic": "NanumGothic-Regular.ttf", "round": "GowunDodum-Regular.ttf",
    "serif": "NanumMyeongjo-Regular.ttf", "dohyeon": "DoHyeon-Regular.ttf",
    "jua": "Jua-Regular.ttf",
}
# v3.214 ④: drawtext fontcolor 용 hex (키워드 → RRGGBB, _FONT_COLOUR 의 역-BGR 원색)
_FONT_HEX = {
    "white": "FFFFFF", "yellow": "FFD700", "pink": "FF6FA5", "sky": "7FD7FF",
}
# ASS PrimaryColour — &H00BBGGRR (알파 00 = 불투명)
_FONT_COLOUR = {
    "white": "&H00FFFFFF",
    "yellow": "&H0000D7FF",  # gold #FFD700
    "pink": "&H00A56FFF",    # #FF6FA5
    "sky": "&H00FFD77F",     # #7FD7FF
}


def font_colour_ass(fontcolor: str) -> str:
    """키워드 또는 hex6(RRGGBB) → ASS &H00BBGGRR."""
    if fontcolor in _FONT_COLOUR:
        return _FONT_COLOUR[fontcolor]
    if _HEX6_RE.match(fontcolor or ""):
        rr, gg, bb = fontcolor[0:2], fontcolor[2:4], fontcolor[4:6]
        return f"&H00{bb.upper()}{gg.upper()}{rr.upper()}"
    return "&H00FFFFFF"


def valid_fontcolor(fontcolor: str) -> bool:
    return fontcolor in STYLE_FONTCOLORS or bool(_HEX6_RE.match(fontcolor or ""))


def _drawtext_hex(fontcolor: str) -> str:
    """v3.214 ④: 키워드 또는 hex6 → drawtext fontcolor 용 RRGGBB (기본 흰색)."""
    if fontcolor in _FONT_HEX:
        return _FONT_HEX[fontcolor]
    if _HEX6_RE.match(fontcolor or ""):
        return fontcolor.upper()
    return "FFFFFF"


# v3.214 ④ 참고: 제목 특수문자(`:`,`'`,`%`,`\\`,`,` …) 는 text= 인라인 이스케이프가
# 아니라 **textfile= + expansion=none** 으로 처리한다 — 필터그래프/옵션/텍스트확장
# 3단 파서의 이스케이프 계층이 ffmpeg 버전별로 미묘해(프로덕션 컨테이너 실측:
# text= 다층 이스케이프는 % 잔류 등 불안정), 파일 경유가 결정적으로 안전.
# expansion=none 은 %{…} 확장 자체를 차단해 제목 내 % 가 무해해진다.


def _style_tuple(layout, shape, lyrics, font, fontcolor, bg, bgblur, bgcolor, bgalpha, fontbold, fontitalic, subpos="low",
                 fontoutline="1", outlinecolor=""):
    # v3.209: 말미 2축 추가(fontoutline, outlinecolor) — 기본값이면 _style_suffix 에서 절단
    return (layout, shape, lyrics, font, fontcolor, bg, bgblur, bgcolor or "", bgalpha, fontbold, fontitalic, subpos,
            fontoutline, outlinecolor or "")


def _style_suffix(*style) -> str:
    """v3.182: 캐시 스타일 suffix — 전축 기본이면 빈 suffix, 아니면 스타일 튜플 md5 8자리.

    v3.209: 말미 신규 축(fontoutline="1", outlinecolor="")이 기본값이면 절단 후 md5 —
    기존 전 조합(기본·비기본)의 object name·과금 ref·video_url 이 배포 전후 비트 동일.
    """
    import hashlib
    style = tuple(style)
    if style[12:14] == ("1", ""):
        style = style[:12]
    if style == _DEFAULT_STYLE_TUPLE[:len(style)]:
        return ""
    return "_" + hashlib.md5("|".join(style).encode()).hexdigest()[:8]


def share_object_name(
    track_id: str, fmt: str = "sns",
    layout: str = "full", shape: str = "square", lyrics: str = "scroll",
    font: str = "basic", fontcolor: str = "white", bg: str = "blur",
    bgblur: str = "mid", bgcolor: str = "", bgalpha: str = "45",
    fontbold: str = "0", fontitalic: str = "0", subpos: str = "low",
    fontoutline: str = "1", outlinecolor: str = "",
) -> str:
    # v3.182: 로고 워터마크 도입(가시 출력 변경) → 캐시 v5 → v6 승격 + 스타일 md5 suffix.
    # v3.214: ⑦ center 자막 기하·wide 커버 0.42H ④ 제목 마퀴 ⑧ PIL 배지 스트립 —
    # 가시 출력 일괄 변경 → 캐시 v6 → v7 승격.
    # v3.215: 정적 요소 PIL 사전 합성(렌더 경로 변경 — 출력 픽셀 동일 목표이나 스케일러
    # 차이로 비트 비동일 가능) → 캐시 v7 → v8 승격. 구 v6/v7 객체는 잔존(자연 만료 —
    # 삭제 금지), 보관함·object 프록시 하위호환. 기존 생성분은 다음 요청 시 1회 재과금.
    suffix = FORMATS.get(fmt, FORMATS["sns"])["suffix"]
    st = _style_tuple(layout, shape, lyrics, font, fontcolor, bg, bgblur, bgcolor, bgalpha, fontbold, fontitalic, subpos,
                      fontoutline, outlinecolor)
    return f"share/v8/{track_id}{suffix}{_style_suffix(*st)}.mp4"


# v3.275: 듀엣 보컬 라벨 — 줄 앞 `[Male] ` 등은 표시용에서 제거(가사 아님). `===` 구분선 줄은 스킵.
_VOCAL_LABEL_RE = re.compile(r"^\s*\[(?:male|female|both|duet|남|여|함께)[^\]]*\]\s*", re.IGNORECASE)
_SEPARATOR_RE = re.compile(r"^[=\-_*~\s]{3,}$")


def _is_collapsed_timeline(raw: list) -> bool:
    """v3.275 — Suno 정렬 붕괴 판정.

    실측(2026-10-04, 101트랙): 듀엣 14곡 중 12곡에서 가사 본문 수십 줄이 곡 시작 1~2초 구간에
    줄 길이 ~0.003s 로 몰리고 나머지 구간은 아웃트로 반복으로만 채워졌다(A·B variant 동시 붕괴).
    검증 없이 서빙하면 "자막이 어긋난다"로 보인다 → 붕괴면 생성 타임스탬프를 버린다(폴백 또는 없음).
    기준: 비태그 줄 ≥5 이고 (a) 길이<0.05s 줄 비율 ≥20% 또는 (b) 1초 창 안에 start 5개 이상 밀집.
    """
    if not isinstance(raw, list):
        return False
    rows = []
    for seg in raw:
        if not isinstance(seg, dict):
            continue
        text = str(seg.get("text") or "").strip()
        if not text or _SECTION_TAG_RE.match(text) or _SEPARATOR_RE.match(text):
            continue
        try:
            rows.append((float(seg.get("start")), float(seg.get("end"))))
        except (TypeError, ValueError):
            continue
    if len(rows) < 5:
        return False
    tiny = sum(1 for st, en in rows if (en - st) < 0.05)
    if tiny / len(rows) >= 0.2:
        return True
    starts = sorted(st for st, _ in rows)
    for i in range(len(starts) - 4):
        if starts[i + 4] - starts[i] <= 1.0:
            return True
    return False


def _filter_segments(raw: list) -> list:
    """타임스탬프 원본 목록 → 자막용 세그먼트 필터·보정 (공용, v130 추출).

    섹션 태그 줄(`[Verse]` 등)·빈 text·start<0·비수치 스킵, end<=start → +0.5,
    SUBTITLE_LEAD 선행 적용. generation·recognized 양쪽 경로에서 사용.
    """
    if not isinstance(raw, list):
        return []
    segments = []
    for seg in raw:
        if not isinstance(seg, dict):
            continue
        text = str(seg.get("text") or "").strip()
        if not text or _SECTION_TAG_RE.match(text) or _SEPARATOR_RE.match(text):
            continue
        # v3.275: 듀엣 보컬 라벨(`[Male] 가사…`) 표시용 제거 — 라벨만 있던 줄은 스킵
        text = _VOCAL_LABEL_RE.sub("", text).strip()
        if not text:
            continue
        try:
            start = float(seg.get("start"))
            end = float(seg.get("end"))
        except (TypeError, ValueError):
            continue
        if start < 0:
            continue
        if end <= start:
            end = start + 0.5
        # 자막 리드(선행): Suno 타임스탬프가 체감 보컬 시작보다 늦게 잡히는 경향이
        # 있어 노래방 방식으로 전체를 SUBTITLE_LEAD 만큼 앞당긴다 (시작·끝 동시
        # 이동 — 줄 간 겹침 없음). 사용자 체감 피드백 기반 (2026-07-23).
        start = max(0.0, start - SUBTITLE_LEAD)
        end = max(start + 0.3, end - SUBTITLE_LEAD)
        segments.append({"text": text, "start": start, "end": end})
    return segments


async def _fetch_lyric_segments(mongo, track: dict) -> list:
    """트랙 → 가사 타임스탬프 세그먼트 조회 (async/motor).

    1순위: generations.variants[variant_index or 0].timestamps (기존 경로 불변).
    2순위(v130 폴백): 결과가 [] 이면 track.recognized_timestamps (Wondera recognize
    파이프라인 저장분)를 동일 필터로 처리. 둘 다 없으면 [].
    """
    raw_gen = await _generation_timestamps(mongo, track)
    # v3.275: Suno 정렬 붕괴본은 서빙 금지 — 틀린 자막보다 자막 없음(또는 recognized 폴백)이 낫다
    if _is_collapsed_timeline(raw_gen):
        logger.warning(
            "[share-video] lyric timeline collapsed — generation timestamps dropped track=%s lines=%d",
            str(track.get("_id", ""))[:8], len(raw_gen),
        )
        raw_gen = []
    segments = _filter_segments(raw_gen)
    source = "generation" if segments else "none"
    if not segments:
        recognized = _filter_segments(track.get("recognized_timestamps") or [])
        if recognized:
            segments = recognized
            source = "recognized"
    logger.info(
        "[share-video] lyric segments source=%s count=%d track=%s",
        source, len(segments), str(track.get("_id", ""))[:8],
    )
    return segments


async def _generation_timestamps(mongo, track: dict) -> list:
    """generation 경로 원본 타임스탬프 조회 — 필터 전 raw 목록 (없으면 [])."""
    generation_id = track.get("generation_id")
    if not generation_id:
        return []
    try:
        from bson import ObjectId

        query_id = (
            ObjectId(generation_id)
            if isinstance(generation_id, str) and ObjectId.is_valid(generation_id)
            else generation_id
        )
        gen = await mongo.generations.find_one({"_id": query_id}, {"variants": 1})
    except Exception:
        logger.warning("[share-video] generations lookup failed gen=%s", generation_id)
        return []
    if not gen:
        return []
    variants = gen.get("variants")
    if not isinstance(variants, list) or not variants:
        return []
    idx = track.get("variant_index") or 0
    if not isinstance(idx, int) or idx < 0 or idx >= len(variants):
        idx = 0
    variant = variants[idx]
    timestamps = variant.get("timestamps") if isinstance(variant, dict) else None
    return timestamps if isinstance(timestamps, list) else []


def _ass_time(seconds: float) -> str:
    """초(float) → ASS 타임스탬프 h:mm:ss.cs"""
    cs = int(round(seconds * 100))
    h, rem = divmod(cs, 360000)
    m, rem = divmod(rem, 6000)
    s, c = divmod(rem, 100)
    return f"{h}:{m:02d}:{s:02d}.{c:02d}"


def _build_ass(
    segments: list, fmt: str = "sns",
    fontname: str = "NanumGothic", colour: str = "&H00FFFFFF",
    bold: int = 0, italic: int = 0, subpos: str = "low",
    outline: int = 3, outline_colour: str = "&H00000000",
    layout: str = "full",
) -> str:
    """세그먼트 → ASS 자막 문자열 (포맷별 PlayRes/Alignment/MarginV).

    v3.181: fontname/colour 파라미터화 — 영상 디렉터 폰트·글자색 선택.
    v3.209: outline(두께 3|0)/outline_colour(&H00BBGGRR) 파라미터화 — 테두리 on/off·색 선택.
    v3.214 ⑦: layout 파라미터화 — MarginV 를 _subpos_positions(fmt, layout) 기하 유도.
    """
    spec = FORMATS.get(fmt, FORMATS["sns"])
    ass = spec["ass"]
    header = (
        "[Script Info]\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {spec['width']}\n"
        f"PlayResY: {spec['height']}\n"
        "WrapStyle: 0\n"
        "ScaledBorderAndShadow: yes\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        f"Style: Default,{fontname},{ass['fontsize']},{colour},{colour},{outline_colour},"
        f"&H00000000,{-1 if bold else 0},{-1 if italic else 0},0,0,100,100,0,0,1,{outline},0,{ass['alignment']},40,40,"
        f"{_subpos_positions(fmt, layout)['margin_v'].get(subpos, ass['margin_v'])},1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
    )
    lines = []
    for seg in segments:
        text = seg["text"].replace("{", "(").replace("}", ")")
        text = text.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\\N")
        lines.append(
            f"Dialogue: 0,{_ass_time(seg['start'])},{_ass_time(seg['end'])},"
            f"Default,,0,0,0,,{text}\n"
        )
    return header + "".join(lines)


# v152 [scroll] 스크롤 자막 레이아웃 — 현재 줄 중앙(\an5) Y=cy, 줄 높이 rh, 표시창 ±window.
# cy/rh 는 워터마크(_WATERMARK) 권역과 화면 경계를 침범하지 않도록 포맷별 튜닝:
#   최하단 줄 중앙 = cy + window*rh, 최상단 줄 중앙 = cy - window*rh.
# - sns  h1920 워터마크 y≈1844: 최하단 1380+2*110=1600 (< 1844) ✓ / 최상단 1160 ✓
# - wide h1080 워터마크 y≈1020: 최하단 720+2*90=900  (< 1020) ✓ / 최상단 540 ✓
# - kakao h2340 워터마크 y≈1287: 최하단 820+2*105=1030 (< 1287) ✓ / 최상단 610 ✓
SCROLL_LAYOUT = {
    "sns": {"cy": 1380, "rh": 110, "window": 2},
    "wide": {"cy": 720, "rh": 90, "window": 2},
    "kakao": {"cy": 820, "rh": 105, "window": 2},
}


def _emph_state(mag: int) -> tuple:
    """스크롤 자막 강조 상태 (거리 |offset| → (alpha, scale%)).

    현재 줄(0)은 불투명·확대, 멀어질수록 흐려지고 축소, 창 밖(>=3)은 완전 투명
    (아래에서 fade-in 하는 진입 줄의 시작 상태로 사용)."""
    if mag <= 0:
        return ("&H00&", 110)
    if mag == 1:
        return ("&H55&", 100)
    if mag == 2:
        return ("&H90&", 92)
    return ("&HFF&", 88)


def _build_ass_scroll(
    segments: list, fmt: str = "sns",
    fontname: str = "NanumGothic", colour: str = "&H00FFFFFF",
    bold: int = 0, italic: int = 0, subpos: str = "low",
    outline: int = 3, outline_colour: str = "&H00000000",
    layout: str = "full",
) -> str:
    """세그먼트 → 스크롤 ASS 자막 문자열 (v152, 브라우저 가사 뷰 v150 미러).

    각 활성 구간 [T_a, T_{a+1}) 마다 현재 줄 a 를 중앙(cy)에 두고 ±window 이웃 줄을
    위/아래 슬롯에 배치. 구간 전환 시 모든 줄이 \\move 로 한 슬롯(rh) 위로 glide 하고
    \\t 로 강조(alpha/scale)를 동시에 보간 → 스택이 매끄럽게 위로 스크롤.
    T_a = segments[a].start, 마지막 경계 T_N = segments[N-1].end.
    실패 없이 항상 문자열 반환 (예외는 호출부에서 잡아 _build_ass 로 폴백)."""
    spec = FORMATS.get(fmt, FORMATS["sns"])
    ass = spec["ass"]
    scroll_default = SCROLL_LAYOUT.get(fmt, SCROLL_LAYOUT["sns"])
    # v3.183: 자막 위치(subpos)에 따라 스크롤 중앙 y 조정.
    # v3.214 ⑦: layout 별 기하 유도 — center 는 rh/window 도 밴드 폭에 맞게 축소.
    pos = _subpos_positions(fmt, layout)
    cy = pos["scroll_cy"].get(subpos, scroll_default["cy"])
    rh, window = pos["scroll_rh"], pos["scroll_window"]
    x = spec["width"] // 2
    # v3.181: 이벤트 인라인 색 재지정용 — "&H00BBGGRR" → "&HBBGGRR&"
    inline_colour = "&H" + colour[4:] + "&"

    header = (
        "[Script Info]\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {spec['width']}\n"
        f"PlayResY: {spec['height']}\n"
        "WrapStyle: 0\n"
        "ScaledBorderAndShadow: yes\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        # Alignment=5 (\an5, 중앙 앵커) — 줄별로 \pos/\move 의 Y 가 세로 중앙점.
        # v3.209: OutlineColour·Outline 파라미터화 (scroll 인라인 오버라이드 \1c·\alpha 는 무수정 —
        # 스타일 기본값이 테두리 색·두께를 전달)
        f"Style: Default,{fontname},{ass['fontsize']},{colour},{colour},{outline_colour},"
        f"&H00000000,{-1 if bold else 0},{-1 if italic else 0},0,0,100,100,0,0,1,{outline},0,5,40,40,0,1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
    )

    n = len(segments)
    if n == 0:
        return header

    # 활성 경계: T[a] = segments[a].start (a<n), 마지막 T[n] = segments[n-1].end.
    bounds = [float(seg["start"]) for seg in segments]
    bounds.append(float(segments[n - 1]["end"]))

    def esc(raw: str) -> str:
        t = str(raw).replace("{", "(").replace("}", ")")
        return t.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\\N")

    events = []
    for a in range(n):
        t_start = bounds[a]
        t_end = bounds[a + 1]
        period = t_end - t_start
        if period <= 0:
            continue
        d = min(0.45, period / 2.0)
        d_ms = max(1, int(round(d * 1000)))
        start_ts = _ass_time(t_start)
        end_ts = _ass_time(t_end)
        for k in range(-window, window + 1):
            j = a + k
            if j < 0 or j >= n:
                continue
            y_cur = cy + k * rh
            y_prev = cy + (k + 1) * rh  # 이전 구간에서 이 줄이 있던 한 슬롯 아래 위치
            target_alpha, target_scale = _emph_state(abs(k))
            if a == 0:
                # 첫 구간: 이전 상태 없음 → 이동/보간 없이 목표 위치·강조로 즉시 배치.
                override = (
                    f"\\an5\\pos({x},{y_cur})\\1c{inline_colour}"
                    f"\\alpha{target_alpha}\\fscx{target_scale}\\fscy{target_scale}"
                )
            else:
                origin_alpha, origin_scale = _emph_state(abs(k + 1))
                override = (
                    f"\\an5\\move({x},{y_prev},{x},{y_cur},0,{d_ms})\\1c{inline_colour}"
                    f"\\alpha{origin_alpha}\\fscx{origin_scale}\\fscy{origin_scale}"
                    f"\\t(0,{d_ms},\\alpha{target_alpha}"
                    f"\\fscx{target_scale}\\fscy{target_scale})"
                )
            text = esc(segments[j]["text"])
            events.append(
                f"Dialogue: 0,{start_ts},{end_ts},Default,,0,0,0,,"
                f"{{{override}}}{text}\n"
            )
    return header + "".join(events)


def share_video_exists(track_id: str, fmt: str = "sns", **style) -> bool:
    """MinIO 에 캐시된 공유영상이 있는지 확인 (blocking). style=share_object_name 키워드."""
    minio_client = get_minio()
    try:
        minio_client.stat_object(
            bucket_name=settings.minio_bucket_music,
            object_name=share_object_name(track_id, fmt, **style),
        )
        return True
    except Exception:
        return False


def _download_cover(minio_client, cover_image_url: str, dest_path: str) -> None:
    """커버 다운로드 — 외부 URL(http/https)이면 httpx, 아니면 이미지 버킷 object."""
    if cover_image_url.startswith(("http://", "https://")):
        resp = httpx.get(cover_image_url, timeout=30.0, follow_redirects=True)
        resp.raise_for_status()
        with open(dest_path, "wb") as f:
            f.write(resp.content)
        return
    response = minio_client.get_object(
        bucket_name=settings.minio_bucket_images,
        object_name=cover_image_url,
    )
    try:
        with open(dest_path, "wb") as f:
            for chunk in response.stream(64 * 1024):
                f.write(chunk)
    finally:
        response.close()
        response.release_conn()


def _download_audio(minio_client, audio_url: str, dest_path: str) -> None:
    response = minio_client.get_object(
        bucket_name=settings.minio_bucket_music,
        object_name=audio_url,
    )
    try:
        with open(dest_path, "wb") as f:
            for chunk in response.stream(64 * 1024):
                f.write(chunk)
    finally:
        response.close()
        response.release_conn()


def _probe_audio_duration(ffmpeg_path: str, audio_path: str) -> float:
    """음원 길이(초) 추출 — 실패 시 0.0 (그 경우 -shortest 만으로 동작)."""
    ffprobe = os.path.join(os.path.dirname(ffmpeg_path), "ffprobe")
    if not os.path.exists(ffprobe):
        ffprobe = "ffprobe"
    try:
        proc = subprocess.run(
            [ffprobe, "-v", "error", "-show_entries", "format=duration",
             "-of", "csv=p=0", audio_path],
            capture_output=True, timeout=30,
        )
        return float(proc.stdout.decode().strip()) if proc.returncode == 0 else 0.0
    except Exception:
        return 0.0


def _filter_path(path: str) -> str:
    """ffmpeg 필터 인자용 경로 안전 조립 — `'`/`:`/`\\` 이스케이프."""
    return path.replace("\\", "\\\\").replace("'", "\\'").replace(":", "\\:")


def _make_center_cover(ffmpeg: str, cover_path: str, out_path: str, size: int, shape: str) -> None:
    """v3.179: center 레이아웃용 마스킹된 정사각 커버 PNG 사전 생성 (1프레임 — geq 를
    본 영상 인코딩(프레임당)에 태우지 않기 위한 사전 패스).

    shape circle=원형 알파, square=둥근 모서리(반지름 10%) 알파.
    """
    half = size / 2.0
    if shape == "circle":
        alpha = (
            f"if(lte(pow(X-{half},2)+pow(Y-{half},2),pow({half},2)),255,0)"
        )
    else:  # rounded square
        r = max(4, int(size * 0.10))
        inner = half - r
        alpha = (
            f"if(lte(pow(max(abs(X-{half})-{inner},0),2)+"
            f"pow(max(abs(Y-{half})-{inner},0),2),pow({r},2)),255,0)"
        )
    vf = (
        f"scale={size}:{size}:force_original_aspect_ratio=increase,"
        f"crop={size}:{size},format=rgba,"
        f"geq=r='r(X,Y)':g='g(X,Y)':b='b(X,Y)':a='{alpha}'"
    )
    cmd = [ffmpeg, "-y", "-i", cover_path, "-frames:v", "1", "-vf", vf, out_path]
    proc = subprocess.run(_nice_cmd(cmd), capture_output=True, timeout=60)  # v3.258 nice
    if proc.returncode != 0 or not os.path.exists(out_path):
        tail = (proc.stderr or b"").decode("utf-8", errors="replace")[-300:]
        raise ShareVideoError(f"center cover mask failed rc={proc.returncode}: {tail}")


def _make_watermark_strip(fmt: str, out_path: str) -> int:
    """v3.214 ⑧: 워터마크 스트립 PNG 런타임 렌더 (PIL) — 폭 W, 투명 배경 1장.

    좌하단: 'AI 생성' 칩 — PlayerScreen 배지 재현·스케일업 (bg rgba(0,0,0,0.55)
      rounded rect radius=0.6fs, padH=0.7fs, padV=0.3fs, 텍스트 rgba(255,255,255,0.85),
      유사볼드 stroke 1 — 번들에 Bold ttf 없음).
    우하단: 'MAIDOL' 록업 — M·DOL #FFFFFF, AI #A855F7(앱 상단바 로고 재현),
      letterSpacing 1px, 박스 없음. 칩과 동일 fontsize·같은 베이스라인(수직 중앙 정렬).
    좌 x=20, 우 끝 x=W−20. ffmpeg 기존 워터마크 입력 슬롯에 그대로 태워 overlay=0:y.

    Returns: 스트립 높이(px, 짝수 보정). 실패 시 예외 (호출부에서 ShareVideoError 매핑).
    """
    from PIL import Image, ImageDraw, ImageFont

    spec = FORMATS.get(fmt, FORMATS["sns"])
    width = spec["width"]
    fs = _BADGE_FONTSIZE.get(fmt, 36)
    font = ImageFont.truetype(os.path.join(FONTS_DIR, _FONT_FILE["basic"]), fs)
    pad_h = int(round(fs * 0.7))
    pad_v = int(round(fs * 0.3))
    radius = max(4, int(round(fs * 0.6)))
    stroke = 1  # 유사 볼드 (앱 배지 w700 대응)
    ascent, descent = font.getmetrics()
    text_h = ascent + descent
    strip_h = text_h + pad_v * 2 + stroke * 2
    strip_h += strip_h % 2  # yuv420p overlay 짝수 보정
    img = Image.new("RGBA", (width, strip_h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    text_y = (strip_h - text_h) // 2

    # 좌측 'AI 생성' 칩 — 칩 박스는 스트립 전고(수직 중앙 기준)
    chip_text = "AI 생성"
    chip_tw = int(round(draw.textlength(chip_text, font=font))) + stroke * 2
    chip_w = chip_tw + pad_h * 2
    draw.rounded_rectangle(
        [20, 0, 20 + chip_w, strip_h - 1], radius=radius, fill=(0, 0, 0, 140),  # 0.55α
    )
    draw.text(
        (20 + pad_h + stroke, text_y), chip_text, font=font,
        fill=(255, 255, 255, 217),  # 0.85α
        stroke_width=stroke, stroke_fill=(255, 255, 255, 217),
    )

    # 우측 MAIDOL 록업 — 문자별 색 + letterSpacing 1px, 우측 끝 x=width−20
    white = (255, 255, 255, 255)
    chars = [("M", white), ("A", _BADGE_PURPLE), ("I", _BADGE_PURPLE),
             ("D", white), ("O", white), ("L", white)]
    letter_spacing = 1
    widths = [draw.textlength(c, font=font) for c, _ in chars]
    total_w = int(round(sum(widths))) + letter_spacing * (len(chars) - 1) + stroke * 2
    x = float(width - 20 - total_w)
    for (ch, colour), cw in zip(chars, widths):
        draw.text((x + stroke, text_y), ch, font=font, fill=colour,
                  stroke_width=stroke, stroke_fill=colour)
        x += cw + letter_spacing
    img.save(out_path)
    logger.info(
        "[watermark] strip rendered fmt=%s size=%dx%d fs=%d chip_w=%d lockup_w=%d",
        fmt, width, strip_h, fs, chip_w, total_w,
    )
    return strip_h


def _compose_static_background(
    ffmpeg: str,
    tmp_dir: str,
    cover_path: str,
    fmt: str,
    layout: str,
    shape: str,
    bg: str,
    bgblur: str,
    bgcolor: str,
    bgalpha: str,
    track_id: str,
) -> str:
    """v3.215: 정적 요소 사전 합성 — 완성된 배경 프레임 1장(PNG, W×H)을 PIL 로 렌더.

    기존 ffmpeg filter_complex 의 정적 체인을 픽셀 배치 동일하게 PIL 로 치환한다.
    ffmpeg → PIL 치환 대응표 (기하 불변 — 기존 상수·수식 그대로):

      [0:v]scale=W:H:force_original_aspect_ratio=increase,crop=W:H (중앙 크롭)
        → ImageOps.fit(cover, (W, H), centering=(0.5, 0.5))
      boxblur={r}:2  (r=_BGBLUR_RADIUS[bgblur] | wide full 고정 20; power=2)
        → ImageFilter.BoxBlur(r) 2회 적용
      drawbox=c=black@0.45:t=fill        → Image.blend(base, 검정, 0.45)
      drawbox=c=0x{bgcolor}@{a}:t=fill   → Image.blend(base, 색, a) (a=bgalpha/100)
      [b][f]overlay=(W-w)/2:{oy}  (center 마스킹 커버 — _make_center_cover 산출 RGBA)
        → alpha_composite(fg, ((W-size)//2, oy))
          oy = round(H*0.42 - size/2) (wide) | int(H*0.32 - size/2) (기존 수식 동일)
      [fg]scale=-2:900 + overlay=(W-w)/2:(H-h)/2  (wide full 센터 커버)
        → resize((round(w0*900/h0) 짝수보정, 900)) 후 중앙 paste
      [b9][N:v]overlay=0:{_WATERMARK_STRIP_Y[fmt]}  (워터마크 스트립)
        → alpha_composite(strip, (0, H - strip_h - _WATERMARK_STRIP_MARGIN[fmt]))

    center 커버 마스킹(geq)은 기존 _make_center_cover(ffmpeg 1프레임 패스)를 그대로
    사용해 마스크 픽셀을 보존하고, 결과 PNG 를 PIL 로 합성만 한다.
    wide 의 블러 배경은 고정 이미지 — 사전 합성에 포함 (kakao 15s 클립도 동일 구조).

    Returns: 합성된 배경 PNG 경로. 실패 시 ShareVideoError.
    """
    from PIL import Image, ImageFilter, ImageOps

    spec = FORMATS.get(fmt, FORMATS["sns"])
    width, height = spec["width"], spec["height"]
    try:
        cover = Image.open(cover_path).convert("RGB")
    except Exception as e:
        raise ShareVideoError(f"cover decode failed: {e}") from e

    # 공통 베이스: scale=W:H:force_original_aspect_ratio=increase,crop=W:H (중앙)
    base = ImageOps.fit(cover, (width, height), method=Image.LANCZOS, centering=(0.5, 0.5))

    if layout == "center":
        # 커버 기하 — 기존 수식 그대로 (0.68 | wide 0.60, 짝수 보정)
        size = int(min(width, height) * (0.60 if fmt == "wide" else 0.68))
        size -= size % 2
        center_cover_path = os.path.join(tmp_dir, "cover_center.png")
        _make_center_cover(ffmpeg, cover_path, center_cover_path, size, shape)
        # 배경 3모드 — bg_chain 치환 (boxblur=r:2 / drawbox t=fill)
        if bg == "blur":
            radius = _BGBLUR_RADIUS.get(bgblur, 24)
            base = base.filter(ImageFilter.BoxBlur(radius)).filter(ImageFilter.BoxBlur(radius))
            base = Image.blend(base, Image.new("RGB", (width, height), (0, 0, 0)), 0.45)
        elif bg == "color" and _HEX6_RE.match(bgcolor or ""):
            alpha = int(bgalpha) / 100.0 if bgalpha in STYLE_BGALPHAS else 0.45
            colour = tuple(int(bgcolor[i:i + 2], 16) for i in (0, 2, 4))
            base = Image.blend(base, Image.new("RGB", (width, height), colour), alpha)
        else:  # clean
            base = Image.blend(base, Image.new("RGB", (width, height), (0, 0, 0)), 0.45)
        # overlay=(W-w)/2:{oy} — wide 0.42H(v3.214 ⑦ 상향) / 그 외 0.32H
        if fmt == "wide":
            oy = round(height * 0.42 - size / 2)
        else:
            oy = int(height * 0.32 - size / 2)
        fg = Image.open(center_cover_path).convert("RGBA")
        base = base.convert("RGBA")
        base.alpha_composite(fg, ((width - size) // 2, oy))
        logger.info(
            "[share-video] center layout track=%s fmt=%s shape=%s size=%d oy=%d (precomposed)",
            track_id, fmt, shape, size, oy,
        )
    elif fmt == "wide":
        # wide full: 배경 crop-fill+boxblur=20:2, 전경 scale=-2:900 중앙 overlay
        base = base.filter(ImageFilter.BoxBlur(20)).filter(ImageFilter.BoxBlur(20))
        fg_w = int(round(cover.width * 900 / cover.height))
        fg_w -= fg_w % 2  # scale=-2 짝수 보정 (ffmpeg 와 ±2px 내 동일 — 중앙 배치라 무영향)
        fg = cover.resize((fg_w, 900), Image.LANCZOS)
        base.paste(fg, ((width - fg_w) // 2, (height - 900) // 2))
        base = base.convert("RGBA")
    else:
        # sns/kakao full: crop-fill 베이스 그대로
        base = base.convert("RGBA")

    # 워터마크 스트립 — overlay=0:{H-h-margin} 치환 (y 수치 동일)
    wm_strip_path = os.path.join(tmp_dir, "wm_strip.png")
    try:
        wm_strip_h = _make_watermark_strip(fmt, wm_strip_path)
    except Exception as e:
        raise ShareVideoError(f"watermark strip render failed: {e}") from e
    wm_y = height - wm_strip_h - _WATERMARK_STRIP_MARGIN.get(fmt, 20)
    strip = Image.open(wm_strip_path).convert("RGBA")
    base.alpha_composite(strip, (0, wm_y))
    logger.info(
        "[watermark] share strip-composite track=%s format=%s h=%d y=%d (precomposed)",
        track_id, fmt, wm_strip_h, wm_y,
    )

    bg_path = os.path.join(tmp_dir, "bg_static.png")
    base.convert("RGB").save(bg_path)
    return bg_path


def generate_share_video(
    track_id: str,
    cover_image_url: str,
    audio_url: str,
    segments: list | None = None,
    fmt: str = "sns",
    layout: str = "full",
    shape: str = "square",
    lyrics_mode: str = "scroll",
    font: str = "basic",
    fontcolor: str = "white",
    bg: str = "blur",
    bgblur: str = "mid",
    bgcolor: str = "",
    bgalpha: str = "45",
    fontbold: str = "0",
    fontitalic: str = "0",
    subpos: str = "low",
    fontoutline: str = "1",
    outlinecolor: str = "",
    title: str = "",
) -> int:
    """커버+음원 다운로드 → ffmpeg 스틸영상 생성 → MinIO 업로드 (blocking).

    segments(v128): 가사 타임스탬프 목록 — 있으면 ASS 자막 burn-in(-r 10).
    fmt(v129): sns(9:16 전체) / wide(16:9 블러배경) / kakao(1080x2340 15s 클립).
    v3.179: layout(full|center)·shape(square|circle)·lyrics_mode(scroll|line) 스타일 축.
    v3.214 ④: title — 가사 없는 곡(연주곡)일 때 자막 대신 제목 drawtext (폭 초과 시
    140px/s 마퀴). 빈 문자열이면 현행(무자막 스틸). Inst 파생 트랙 제외는 라우트 책임.
    Returns: 생성된 mp4 크기(bytes). 실패 시 ShareVideoError.

    v205: heavy_job_slot 안에서 실행 (동시 상한). 이 함수는 blocking 이라
    호출자는 반드시 asyncio.to_thread 등 워커 스레드로 태워야 하며
    (routes/tracks.py 가 그렇게 함), 슬롯 acquire 도 그 스레드 안에서 일어난다.
    슬롯은 대기 무제한, 실행은 기존 SHARE_VIDEO_TIMEOUT 유지 — 중첩 변화 없음.
    """
    from .heavy_jobs import heavy_job_slot

    with heavy_job_slot("share_video", f"{track_id}:{fmt}:{layout}:{shape}:{lyrics_mode}:{font}:{fontcolor}:{bg}:{bgblur}:{bgcolor}:{bgalpha}:{fontbold}:{fontitalic}:{subpos}:{fontoutline}:{outlinecolor}"):
        return _generate_share_video_impl(
            track_id, cover_image_url, audio_url, segments, fmt, layout, shape, lyrics_mode,
            font, fontcolor, bg, bgblur, bgcolor, bgalpha, fontbold, fontitalic, subpos,
            fontoutline, outlinecolor, title,
        )


def _generate_share_video_impl(
    track_id: str,
    cover_image_url: str,
    audio_url: str,
    segments: list | None = None,
    fmt: str = "sns",
    layout: str = "full",
    shape: str = "square",
    lyrics_mode: str = "scroll",
    font: str = "basic",
    fontcolor: str = "white",
    bg: str = "blur",
    bgblur: str = "mid",
    bgcolor: str = "",
    bgalpha: str = "45",
    fontbold: str = "0",
    fontitalic: str = "0",
    subpos: str = "low",
    fontoutline: str = "1",
    outlinecolor: str = "",
    title: str = "",
) -> int:
    _style_kw = dict(layout=layout, shape=shape, lyrics=lyrics_mode, font=font,
                     fontcolor=fontcolor, bg=bg, bgblur=bgblur, bgcolor=bgcolor,
                     bgalpha=bgalpha, fontbold=fontbold, fontitalic=fontitalic, subpos=subpos,
                     fontoutline=fontoutline, outlinecolor=outlinecolor)
    ffmpeg = _get_ffmpeg_path()
    if not ffmpeg:
        raise ShareVideoError("ffmpeg not available")
    if fmt not in FORMATS:
        raise ShareVideoError(f"unknown format: {fmt}")
    spec = FORMATS[fmt]

    segments = segments or []
    # kakao(v129): 15초 클립 — t0 = 첫 가사 세그먼트 start−0.5s(음수면 0, 세그먼트 없으면 0).
    # ASS 시각은 t0 기준으로 offset 보정, 클립(0~15s) 범위 세그먼트만 포함.
    clip_t0 = 0.0
    clip_len = spec["clip"]
    if clip_len:
        if segments:
            clip_t0 = max(0.0, segments[0]["start"] - 0.5)
        clipped = []
        for seg in segments:
            start = seg["start"] - clip_t0
            end = min(seg["end"] - clip_t0, clip_len)
            if 0 <= start < clip_len and end > start:
                clipped.append({"text": seg["text"], "start": start, "end": end})
        logger.info(
            "[share-video] kakao clip track=%s t0=%.2f segments=%d→%d",
            track_id, clip_t0, len(segments), len(clipped),
        )
        segments = clipped
    subtitled = bool(segments)
    # v3.214 ④: 가사 없는 곡(연주곡) + 제목 존재 → 자막 대신 제목 drawtext (마퀴/정적)
    title_mode = bool((title or "").strip()) and not subtitled
    minio_client = get_minio()
    with tempfile.TemporaryDirectory(prefix="share_video_") as tmp_dir:
        cover_ext = os.path.splitext(cover_image_url.split("?")[0])[1] or ".png"
        audio_ext = os.path.splitext(audio_url)[1] or ".mp3"
        cover_path = os.path.join(tmp_dir, f"cover{cover_ext}")
        audio_path = os.path.join(tmp_dir, f"audio{audio_ext}")
        out_path = os.path.join(tmp_dir, "out.mp4")

        try:
            _download_cover(minio_client, cover_image_url, cover_path)
        except Exception as e:
            raise ShareVideoError(f"cover download failed: {e}") from e
        try:
            _download_audio(minio_client, audio_url, audio_path)
        except Exception as e:
            raise ShareVideoError(f"audio download failed: {e}") from e

        width, height = spec["width"], spec["height"]
        # v3.215: 정적 요소(커버 배치·배경·워터마크 스트립)를 PIL 배경 프레임 1장으로
        # 사전 합성 — ffmpeg 에는 단일 -loop 입력 + 동적 필터(ASS/마퀴)만 남긴다.
        compose_started = time.monotonic()
        bg_static_path = _compose_static_background(
            ffmpeg, tmp_dir, cover_path, fmt, layout, shape,
            bg, bgblur, bgcolor, bgalpha, track_id,
        )
        logger.info(
            "[share-video] static precompose done track=%s format=%s layout=%s elapsed=%.2fs",
            track_id, fmt, layout, time.monotonic() - compose_started,
        )
        # 동적 필터만 조립 — 자막(ASS)/제목 마퀴(drawtext). 없으면 filter 자체 생략.
        vf = None
        if subtitled:
            ass_path = os.path.join(tmp_dir, "subs.ass")
            # v152: 스크롤 자막 우선 — 실패 시 기존 단일 줄(_build_ass) 로 폴백.
            # v3.179: lyrics_mode='line' 이면 처음부터 단일 줄(_build_ass — 한 줄씩 표시).
            try:
                _fn = _FONT_NAME.get(font, "NanumGothic")
                _fc = font_colour_ass(fontcolor)
                _fb, _fi = int(fontbold == "1"), int(fontitalic == "1")
                # v3.209: 자막 테두리 — off 면 두께 0, 색은 hex6 → ASS BGR(&H00BBGGRR)
                _ol = 3 if fontoutline == "1" else 0
                _oc = font_colour_ass(outlinecolor) if outlinecolor else "&H00000000"
                logger.info(
                    "[share-video] outline track=%s fontoutline=%s outlinecolor=%s ass=%s w=%d",
                    track_id, fontoutline, outlinecolor or "default", _oc, _ol,
                )
                if lyrics_mode == "line":
                    ass_body = _build_ass(segments, fmt, _fn, _fc, _fb, _fi, subpos, _ol, _oc, layout)
                    logger.info(
                        "[share-video] ass-line track=%s format=%s segments=%d",
                        track_id, fmt, len(segments),
                    )
                else:
                    ass_body = _build_ass_scroll(segments, fmt, _fn, _fc, _fb, _fi, subpos, _ol, _oc, layout)
                    events_count = ass_body.count("Dialogue:")
                    logger.info(
                        "[share-video] ass-scroll track=%s format=%s segments=%d "
                        "events=%d fps=20",
                        track_id, fmt, len(segments), events_count,
                    )
            except Exception:
                logger.exception(
                    "[share-video] ass build failed, fallback to single-line "
                    "track=%s format=%s mode=%s",
                    track_id, fmt, lyrics_mode,
                )
                ass_body = _build_ass(
                    segments, fmt,
                    _FONT_NAME.get(font, "NanumGothic"), font_colour_ass(fontcolor),
                    int(fontbold == "1"), int(fontitalic == "1"), subpos,
                    3 if fontoutline == "1" else 0,
                    font_colour_ass(outlinecolor) if outlinecolor else "&H00000000",
                    layout,
                )
            with open(ass_path, "w", encoding="utf-8") as f:
                f.write(ass_body)
            logger.info(
                "[share-video] ass build track=%s format=%s segments=%d fontsdir=%s",
                track_id, fmt, len(segments), FONTS_DIR,
            )
            vf = f"[0:v]ass='{_filter_path(ass_path)}':fontsdir='{_filter_path(FONTS_DIR)}'"
        elif title_mode:
            # v3.214 ④: 연주곡 제목 drawtext — 폭 초과 시에만 우→좌 140px/s 무한 마퀴,
            # 아니면 중앙 정적. y = subpos 밴드의 line 모드 좌표 (alignment 기준 환산).
            # 제목은 textfile= 로 전달(이스케이프 불요) + expansion=none (모듈 상단 주석).
            pos_mv = _subpos_positions(fmt, layout)["margin_v"].get(
                subpos, spec["ass"]["margin_v"]
            )
            # sns/wide: alignment=2(하단 마진) → y = h−MarginV−th, kakao: alignment=8(상단) → y = MarginV
            y_expr = str(pos_mv) if spec["ass"]["alignment"] == 8 else f"h-{pos_mv}-th"
            x_expr = "if(gt(text_w,w-80),w-mod(t*140,text_w+w),(w-text_w)/2)"
            fontfile = os.path.join(FONTS_DIR, _FONT_FILE.get(font, _FONT_FILE["basic"]))
            title_path = os.path.join(tmp_dir, "title.txt")
            with open(title_path, "w", encoding="utf-8") as f:
                f.write(title.strip())
            border = ""
            if fontoutline == "1":
                border = f":borderw=3:bordercolor=0x{_drawtext_hex(outlinecolor) if outlinecolor else '000000'}"
            vf = (
                f"[0:v]drawtext=fontfile='{_filter_path(fontfile)}'"
                f":textfile='{_filter_path(title_path)}':expansion=none"
                f":fontsize={spec['ass']['fontsize']}"
                f":fontcolor=0x{_drawtext_hex(fontcolor)}{border}"
                f":x='{x_expr}':y='{y_expr}'"
            )
            logger.info(
                "[share-video] title-marquee track=%s format=%s layout=%s subpos=%s "
                "margin_v=%d title_len=%d",
                track_id, fmt, layout, subpos, pos_mv, len(title.strip()),
            )
        # v3.215: 워터마크 스트립은 _compose_static_background 에서 이미 합성됨 —
        # 별도 -loop 입력·overlay 없음 (v3.214 ⑧ 스트립 렌더 자체는 그대로 재사용).
        if vf is not None:
            vf += "[v]"
        # 자막 있으면 -r 20 (v152 스크롤 glide 부드럽게), 없으면 기존 -r 2 (스틸) — 3포맷 공통.
        # v3.214 ④: 제목 마퀴도 -r 20 (마퀴 이동 프레임 — 스틸 -r 2 금지)
        # v3.215: -loop 이미지 입력의 -framerate 를 출력 -r 과 일치 — 기본 25fps 로
        # 매 프레임 PNG 재디코드되던 낭비 제거 (입력 옵션이므로 -i 앞에 위치).
        frame_rate = "20" if (subtitled or title_mode) else "2"
        cmd = [ffmpeg, "-y", "-framerate", frame_rate, "-loop", "1", "-i", bg_static_path]
        if clip_len and clip_t0 > 0:
            cmd += ["-ss", f"{clip_t0:.3f}"]  # 음원 입력 seek (kakao 클립 시작점)
        cmd += ["-i", audio_path]
        if vf is not None:
            cmd += ["-filter_complex", vf, "-map", "[v]"]
        else:
            cmd += ["-map", "0:v"]  # 동적 필터 없음 — 사전 합성 배경 그대로 (무자막 스틸)
        cmd += [
            "-map", "1:a",
            "-c:v", "libx264", "-tune", "stillimage", "-preset", "veryfast",
            "-r", frame_rate, "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "192k",
            "-shortest", "-movflags", "+faststart",
            # v137 [watermark]: 비가시 — 컨테이너 메타데이터 comment.
            *video_metadata_args(),
        ]
        # -loop 1 + -shortest 는 muxer interleave 로 영상이 음원보다 ~10s 길어질
        # 수 있어, 출력 길이를 -t 로 정확히 자름.
        # kakao: 고정 15s. 그 외: 음원 길이 probe (실패 시 -shortest 만).
        if clip_len:
            cmd += ["-t", f"{clip_len:.3f}"]
        else:
            audio_duration = _probe_audio_duration(ffmpeg, audio_path)
            if audio_duration > 0:
                cmd += ["-t", f"{audio_duration:.3f}"]
        cmd.append(out_path)
        started = time.monotonic()
        try:
            proc = subprocess.run(_nice_cmd(cmd), capture_output=True, timeout=SHARE_VIDEO_TIMEOUT)  # v3.258 nice
        except subprocess.TimeoutExpired:
            logger.error(
                "[share-video] ffmpeg timeout track=%s format=%s (%ss)",
                track_id, fmt, SHARE_VIDEO_TIMEOUT,
            )
            raise ShareVideoError(f"ffmpeg timeout ({SHARE_VIDEO_TIMEOUT}s)")
        if proc.returncode != 0:
            stderr_tail = (proc.stderr or b"").decode("utf-8", errors="replace")[-500:]
            logger.error(
                "[share-video] ffmpeg failed track=%s format=%s rc=%s stderr_tail=%s",
                track_id, fmt, proc.returncode, stderr_tail,
            )
            raise ShareVideoError(f"ffmpeg rc={proc.returncode}")

        elapsed = time.monotonic() - started
        size = os.path.getsize(out_path)
        logger.info(
            "[share-video] ffmpeg done rc=0 track=%s format=%s elapsed=%.1fs size=%d bytes "
            "segments=%d subtitled=%s",
            track_id, fmt, elapsed, size, len(segments), subtitled,
        )

        # 동시 중복 생성 가드: 업로드 직전 재확인 — 이미 다른 요청이 올렸으면 스킵.
        if share_video_exists(track_id, fmt, **_style_kw):
            logger.info(
                "[share-video] concurrent cache detected track=%s format=%s — skip upload",
                track_id, fmt,
            )
            return size

        with open(out_path, "rb") as f:
            minio_client.put_object(
                bucket_name=settings.minio_bucket_music,
                object_name=share_object_name(track_id, fmt, **_style_kw),
                data=f,
                length=size,
                content_type="video/mp4",
            )
        return size
